spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
  bootstrap:
    admin:
      enabled: true
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:postgres}
      role: ${ADMIN_ROLE:ADMIN}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
